repos:
  - repo: local
    hooks:
      - id: lint-js
        name: "lint typescript and javascript"
        entry: /usr/bin/env bunx eslint
        files: '\.jsx?$|\.tsx?$'
        language: script
        description: "Checks JS/TS code according to the package's linter configuration"
  - repo: local
    hooks:
      - id: lint-config
        name: "lint config files"
        entry: /usr/bin/env bunx prettier -c
        files: '\.json$|\.yaml$|\.toml$|\.yml$'
        language: script
        description: "Checks config files according to the package's linter configuration"
  - repo: local
    hooks:
      - id: lint-docs
        name: "lint documentation files"
        entry: /usr/bin/env bunx prettier -c
        files: '\.md$'
        language: script
        description: "Checks documentation files according to the package's linter configuration"
