repos:
  - repo: local
    hooks:
      - id: lint-js
        name: "lint typescript and javascript"
        entry: /usr/bin/env bunx oxlint --type-aware
        files: '\.jsx?$|\.tsx?$'
        language: script
        description: "Checks JS/TS code according to the package's linter configuration"
      - id: format
        name: "check formatting"
        entry: /usr/bin/env bunx oxfmt --check
        files: '\.jsx?$|\.tsx?$|\.json$|\.yaml$|\.yml$|\.md$'
        language: script
        description: "Checks file formatting"
